traefik:
  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
  ingressRoute:
    dashboard:
      enabled: true
  ports:
    web:
      exposedPort: 80
  service:
    type: LoadBalancer
    spec:
      loadBalancerIP: 192.168.0.250
