traefik:
  providers:
    kubernetesCRD:
      enabled: true
  ingressRoute:
    dashboard:
      enabled: true
      matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      entryPoints:
        - web
  ports:
    web:
      redirectTo:
        port: websecure
  service:
    type: LoadBalancer
    spec:
      loadBalancerIP: 192.168.0.250
