apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    tunnel: homelab-k3s
    credentials-file: /etc/cloudflared/creds/token
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: "*.k3s.knoesen.link"
        service: http://traefik.network.svc.cluster.local:80
      - service: http_status:404
