
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: traefik.gretna-en-werner.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik-api
            port:
              name: traefik