apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  config.yaml: |
    {{- if .Values.ingress.enabled }}
    ingress:
    {{- range .Values.ingress.rules }}
      {{- if .hostname }}
      - hostname: {{ .hostname | quote }}
        service: {{ .service | quote }}
        {{- if .originRequest }}
        originRequest:
          {{- if .originRequest.noTLSVerify }}
          noTLSVerify: {{ .originRequest.noTLSVerify }}
          {{- end }}
        {{- end }}
      {{- else }}
      - service: {{ .service | quote }}
      {{- end }}
    {{- end }}
    {{- end }}
