apiVersion: v2
name: loadbalancer
description: A Helm chart for Kubernetes that will support a networking layer of the homelab.

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: metallb
    version: 0.15.2
    repository: "file://charts/metallb"
