apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      pod: cloudflared
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        pod: cloudflared
    spec:
      {{- if .Values.securityContext }}
      securityContext:
        {{- if .Values.securityContext.sysctls }}
        sysctls:
        {{- range .Values.securityContext.sysctls }}
          - name: {{ .name }}
            value: {{ .value | quote }}
        {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: cloudflared
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.tunnelToken.secretName }}
                  key: {{ .Values.tunnelToken.secretKey }}
          command:
            - cloudflared
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            {{- if .Values.cloudflared.noAutoUpdate }}
            - --no-autoupdate
            {{- end }}
            {{- if .Values.cloudflared.logLevel }}
            - --loglevel
            - {{ .Values.cloudflared.logLevel }}
            {{- end }}
            {{- if .Values.cloudflared.metrics.enabled }}
            - --metrics
            - "0.0.0.0:{{ .Values.cloudflared.metrics.port }}"
            {{- end }}
            - run
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared
              readOnly: true
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
